from __future__ import annotations

ADMIN_TOKEN_ENV = "INKMOMENT_AUTH_ADMIN_TOKEN"
ADMIN_COOKIE_NAME = "inkmoment_admin_token"
CONFIRM_ACTION_VALUE = "CONFIRM"
HSTS_VALUE = "max-age=31536000; includeSubDomains"
DASHBOARD_PAGE_SIZE_CHOICES = (6, 10, 20, 50)
DEFAULT_DASHBOARD_PAGE_SIZE = 6
ADMIN_API_LIST_LIMIT_MAX = 500
ADMIN_EXPORT_LIMIT_MAX = 5000
