AUTH_SERVER_URL_ENV = "INKMOMENT_AUTH_SERVER_URL"
AUTH_CHECK_INTERVAL_SECONDS = 600
AUTH_SESSION_SETTING = "auth_session"
AUTH_TIMEOUT_SECONDS = 8
AUTH_DISABLED_REASON = "auth_server_not_configured"
DEVICE_FINGERPRINT_VERSION = "inkmoment-device-v1"
