"""Compatibility facade for session builder services."""

from server.services.session_builder import (
    AUTO_KICK_MARGIN,
    AUTO_WIN_MARGIN,
    PRESCREEN_PROFILES,
    _aesthetic_score,
    _auto_reject_reason,
    _composite_score,
    _face_quality_score,
    _fatal_flags,
    _identify_main_subjects,
    _init_group_with_prescreen,
    _init_group_without_prescreen,
    _meta_entry,
    _prescreen_rejections,
    _quality_flags,
    _quality_score,
    _subject_sharpness,
    build_prescreen_session_from_infos,
    build_session_from_groups,
)

__all__ = [
    "AUTO_KICK_MARGIN",
    "AUTO_WIN_MARGIN",
    "PRESCREEN_PROFILES",
    "_aesthetic_score",
    "_auto_reject_reason",
    "_composite_score",
    "_face_quality_score",
    "_fatal_flags",
    "_identify_main_subjects",
    "_init_group_with_prescreen",
    "_init_group_without_prescreen",
    "_meta_entry",
    "_prescreen_rejections",
    "_quality_flags",
    "_quality_score",
    "_subject_sharpness",
    "build_prescreen_session_from_infos",
    "build_session_from_groups",
]
