from __future__ import annotations

PASSWORD_ALGORITHM = "pbkdf2_sha256"
PASSWORD_ITERATIONS = 260_000
UNBIND_PENALTY_DAYS = 3
MAX_BOUND_DEVICES = 1
ADMIN_LOGIN_FAILURE_LIMIT = 5
ADMIN_LOGIN_LOCK_SECONDS = 15 * 60
USER_LOGIN_FAILURE_LIMIT = 5
USER_LOGIN_LOCK_SECONDS = 15 * 60
USER_SESSION_TTL_SECONDS = 24 * 60 * 60
ADMIN_SESSION_TTL_SECONDS = 12 * 60 * 60
DEVICE_DETAILS_MAX_FIELDS = 80
DEVICE_DETAILS_MAX_VALUE_LENGTH = 240

ADMIN_ROLE_OWNER = "owner"
ADMIN_ROLE_OPERATOR = "operator"
ADMIN_ROLE_AUDITOR = "auditor"
ADMIN_ROLE_AGENT = "agent"

ADMIN_PERMISSION_ADMINS_READ = "admins:read"
ADMIN_PERMISSION_ADMINS_WRITE = "admins:write"
ADMIN_PERMISSION_USERS_READ = "users:read"
ADMIN_PERMISSION_USERS_WRITE = "users:write"
ADMIN_PERMISSION_CDKS_READ = "cdks:read"
ADMIN_PERMISSION_CDKS_WRITE = "cdks:write"

ADMIN_ROLE_PERMISSIONS = {
    ADMIN_ROLE_OWNER: {"*"},
    ADMIN_ROLE_OPERATOR: {
        ADMIN_PERMISSION_USERS_READ,
        ADMIN_PERMISSION_USERS_WRITE,
        ADMIN_PERMISSION_CDKS_READ,
        ADMIN_PERMISSION_CDKS_WRITE,
    },
    ADMIN_ROLE_AGENT: {
        ADMIN_PERMISSION_USERS_READ,
        ADMIN_PERMISSION_CDKS_READ,
        ADMIN_PERMISSION_CDKS_WRITE,
    },
    ADMIN_ROLE_AUDITOR: {
        ADMIN_PERMISSION_USERS_READ,
        ADMIN_PERMISSION_CDKS_READ,
    },
}
